"""
detectors.py
------------
Bounded Hunter: Two-gate detector for bounded non-periodic C2 beaconing
using irrational rotation sequences.

Target: C2 beacons where sleep intervals are bounded (e.g., 30-120 seconds),
non-repeating, and deterministic — generated by irrational rotation:

    sleep(min + (max - min) * frac(n * alpha))

where alpha is an irrational number (phi, sqrt(2), pi, etc.) and frac()
takes the fractional part. The resulting intervals fill the [min, max]
range uniformly with no repeats and a specific structural property.

These schedules evade EVERYTHING:
  - RITA / AC-Hunter    (no periodicity, moderate CV, no modal interval)
  - All 6 Hunter tools  (no growth trend — intervals are bounded)
  - Reverse Scanner     (no shrinkage trend either)

The intervals look like noisy application traffic to every existing detector.
But they carry a mathematical fingerprint: the THREE-GAP THEOREM.

Three-Gap Theorem (Steinhaus/Sos 1958):
  For any irrational alpha and any N, the points {frac(n*alpha), n=1..N}
  partition [0,1] into gaps of AT MOST THREE distinct lengths. Always.
  Random uniform samples produce N distinct gap lengths.
  This is the testable structural difference.

Two-gate pipeline:

  Gate 1 -- Bounded Non-Periodic Confirmation
    Intervals must be bounded (range ratio < 5), non-constant (CV > 0.10),
    and non-trending (low regression slope — rules out all growth families).

  Gate 2 -- Three-Gap + Low Discrepancy Test
    Normalize intervals to [0,1], sort, measure gap lengths.
    (a) Gap clusters: count distinct gap lengths (tolerance-based).
        Rotation sequences: <= 4 clusters. Random: many clusters.
    (b) Star discrepancy: D* measures how uniformly values fill [0,1].
        Rotation: D* is low (uniform fill). Cycling patterns: D* is high.
    Both (a) and (b) must pass. This rejects both random traffic (fails a)
    and cycling/retry patterns (fails b).

Classification labels:
  ROTATION_BEACON     -- Both gates pass (bounded quasi-random schedule)
  REGULAR_BEACON      -- Constant-interval periodic
  JITTERED_BEACON     -- Jittered periodic (bounded but low CV)
  BACKGROUND          -- No detectable structure
  INSUFFICIENT_DATA   -- Fewer than MIN_INTERVALS connections
"""

import numpy as np
from scipy import stats as sp_stats

# ============================================================
# Constants
# ============================================================

PHI = (1.0 + np.sqrt(5.0)) / 2.0  # Golden ratio — most common rotation base

MIN_INTERVALS      = 8       # need enough intervals for gap clustering
MAX_RANGE_RATIO    = 5.0     # max(ICI)/min(ICI) — must be bounded
MIN_CV             = 0.10    # min CV — excludes near-constant
MAX_TREND          = 0.03    # max |slope|/mean — excludes growth/shrinkage
MAX_GAP_CLUSTERS   = 4       # max distinct gap lengths (3 + 1 for jitter)
MAX_DISCREPANCY    = 0.20    # max star discrepancy D*
N_BOOTSTRAP        = 300     # random uniform comparison trials
MAX_P              = 0.05    # max p-value for gap cluster test


# ============================================================
# Gate 1: Bounded Non-Periodic Confirmation
# ============================================================

def bounded_test(timestamps, max_range=MAX_RANGE_RATIO, min_cv=MIN_CV,
                 max_trend=MAX_TREND):
    """
    Gate 1: Confirm intervals are bounded, variable, and non-trending.

    This gate separates "bounded aperiodic" from everything else:
      - Growth families (Fibonacci, Tribonacci, etc.): fail trend check
      - Constant beacons: fail CV check
      - Highly variable traffic (wide range): fail range check

    Parameters
    ----------
    timestamps : array-like
    max_range  : float (max ratio of largest to smallest ICI)
    min_cv     : float (min coefficient of variation)
    max_trend  : float (max |slope|/mean in linear regression)

    Returns
    -------
    dict with: n_intervals, range_ratio, cv, trend, label, beacon_score
    """
    ts = np.array(sorted(timestamps), dtype=float)
    icis = np.diff(ts)
    valid = icis[icis > 1e-6]
    n = len(valid)

    base = {
        "n_intervals": n, "range_ratio": None, "cv": None,
        "trend": None, "label": "INSUFFICIENT", "beacon_score": 0.0,
    }

    if n < MIN_INTERVALS:
        return base

    ici_min = float(valid.min())
    ici_max = float(valid.max())
    ici_mean = float(valid.mean())
    cv = float(valid.std() / ici_mean) if ici_mean > 0 else 0
    range_ratio = ici_max / max(ici_min, 1e-10)

    # Trend: normalized slope of linear regression
    x = np.arange(n, dtype=float)
    slope, _, _, _, _ = sp_stats.linregress(x, valid)
    trend = abs(slope) / max(ici_mean, 1e-10)

    result = {
        "n_intervals": n,
        "range_ratio": round(range_ratio, 3),
        "cv": round(cv, 4),
        "trend": round(trend, 4),
    }

    if range_ratio > max_range:
        result["label"] = "WIDE_RANGE"
        result["beacon_score"] = 0.0
    elif cv < min_cv:
        result["label"] = "NEAR_CONSTANT"
        result["beacon_score"] = 0.0
    elif trend > max_trend:
        result["label"] = "TRENDING"
        result["beacon_score"] = 0.0
    else:
        result["label"] = "BOUNDED"
        # Score: higher for tighter range and lower trend
        score = max(0.0, 1.0 - trend / max_trend) * max(0.0, 1.0 - range_ratio / max_range)
        result["beacon_score"] = round(score, 3)

    return result


# ============================================================
# Gate 2: Three-Gap + Low Discrepancy Test
# ============================================================

def star_discrepancy(x):
    """
    Compute star discrepancy D* of values in [0, 1].
    Measures how far the empirical distribution deviates from uniform.
    Lower = more uniform. Rotation sequences have D* ~ 1/N.
    Random uniform has D* ~ 1/(2√N).
    """
    xs = np.sort(x)
    n = len(xs)
    i = np.arange(1, n + 1, dtype=float)
    d_plus = float(np.max(i / n - xs))
    d_minus = float(np.max(xs - (i - 1) / n))
    return max(d_plus, d_minus)


def count_gap_clusters(gaps, rel_tol=0.40):
    """
    Count distinct gap length clusters using tolerance-based grouping.
    For exact rotation: 2-3 clusters. For random: many clusters.
    Tolerance is set high (0.40) to handle jitter blurring of gap boundaries.
    """
    if len(gaps) < 2:
        return len(gaps)
    sg = np.sort(gaps)
    clusters = 1
    cluster_ref = sg[0]
    for i in range(1, len(sg)):
        # New cluster if gap differs from reference by more than rel_tol
        if cluster_ref > 1e-10 and (sg[i] - cluster_ref) / cluster_ref > rel_tol:
            clusters += 1
            cluster_ref = sg[i]
        elif cluster_ref <= 1e-10 and sg[i] > 1e-10:
            clusters += 1
            cluster_ref = sg[i]
    return clusters


def three_gap_test(timestamps, max_clusters=MAX_GAP_CLUSTERS,
                   max_discrepancy=MAX_DISCREPANCY,
                   n_bootstrap=N_BOOTSTRAP, max_p=MAX_P):
    """
    Gate 2: Three-gap structure test with discrepancy confirmation.

    Tests whether the interval values, when normalized to [0,1] and sorted,
    produce at most 3-4 distinct gap lengths (three-gap theorem signature)
    AND fill the range uniformly (low star discrepancy).

    The combination rejects:
      - Random traffic: many gap clusters (fails cluster test)
      - Cycling patterns: few gaps but high discrepancy (fails discrepancy)
      - Growth families: rejected by Gate 1 before this runs

    Parameters
    ----------
    timestamps      : array-like
    max_clusters    : int (max gap clusters, default 4)
    max_discrepancy : float (max D*, default 0.20)
    n_bootstrap     : int
    max_p           : float

    Returns
    -------
    dict with: n_gaps, gap_clusters, discrepancy, p_value, label, beacon_score
    """
    ts = np.array(sorted(timestamps), dtype=float)
    icis = np.diff(ts)
    valid = icis[icis > 1e-6]
    n = len(valid)

    base = {
        "n_gaps": 0, "gap_clusters": None, "discrepancy": None,
        "p_value": None, "gap_lengths": None,
        "label": "INSUFFICIENT", "beacon_score": 0.0,
    }

    if n < MIN_INTERVALS:
        return base

    # Normalize to [0, 1]
    v_min, v_max = float(valid.min()), float(valid.max())
    if v_max - v_min < 1e-10:
        base["label"] = "DEGENERATE"
        return base

    normalized = (valid - v_min) / (v_max - v_min)

    # Sort and compute gaps
    sorted_norm = np.sort(normalized)
    gaps = np.diff(sorted_norm)
    # Include edge gaps (from 0 to first point, from last point to 1)
    all_gaps = np.concatenate([[sorted_norm[0]],
                                gaps,
                                [1.0 - sorted_norm[-1]]])

    n_gaps = len(all_gaps)
    clusters = count_gap_clusters(all_gaps)
    disc = star_discrepancy(normalized)

    # Extract representative gap lengths for reporting
    sg = np.sort(all_gaps)
    unique_gaps = [sg[0]]
    for g in sg[1:]:
        if unique_gaps[-1] > 1e-10 and (g - unique_gaps[-1]) / unique_gaps[-1] > 0.15:
            unique_gaps.append(g)
        elif unique_gaps[-1] <= 1e-10 and g > 1e-10:
            unique_gaps.append(g)

    result = {
        "n_gaps": n_gaps,
        "gap_clusters": clusters,
        "discrepancy": round(disc, 4),
        "gap_lengths": [round(g, 4) for g in unique_gaps[:5]],
    }

    if clusters > max_clusters:
        result["label"] = "TOO_MANY_GAPS"
        result["p_value"] = None
        result["beacon_score"] = 0.0
        return result

    if disc > max_discrepancy:
        result["label"] = "HIGH_DISCREPANCY"
        result["p_value"] = None
        result["beacon_score"] = 0.0
        return result

    # Bootstrap: how often do random uniform samples produce <= clusters gaps?
    rng = np.random.default_rng(0)
    extreme = 0
    for _ in range(n_bootstrap):
        rand_vals = rng.uniform(0, 1, n)
        rand_sorted = np.sort(rand_vals)
        rand_gaps = np.concatenate([[rand_sorted[0]],
                                     np.diff(rand_sorted),
                                     [1.0 - rand_sorted[-1]]])
        rand_clusters = count_gap_clusters(rand_gaps)
        if rand_clusters <= clusters:
            extreme += 1
    p_value = float(extreme / n_bootstrap)

    result["p_value"] = round(p_value, 4)

    if p_value < max_p:
        label = "THREE_GAP"
        score = max(0.0, 1.0 - clusters / (max_clusters + 1))
        score *= max(0.0, 1.0 - disc / max_discrepancy)
    else:
        label = "NOT_THREE_GAP"
        score = 0.0

    result["label"] = label
    result["beacon_score"] = round(score, 3)
    return result


# ============================================================
# classify_flow
# ============================================================

def classify_flow(timestamps, session_gap=5.0, min_pkts=MIN_INTERVALS,
                  connection_level=False):
    """
    Full two-gate pipeline for bounded quasi-random beacons.

    Classification hierarchy:
      ROTATION_BEACON  -- Both gates pass (irrational rotation schedule)
      REGULAR_BEACON   -- Constant-interval periodic
      JITTERED_BEACON  -- Bounded low-CV periodic
      BACKGROUND       -- No detectable structure
      INSUFFICIENT_DATA
    """
    ts = sorted(timestamps)
    n = len(ts)

    if n < min_pkts + 1:
        return {"classification": "INSUFFICIENT_DATA", "confidence": 0.0,
                "n_connections": n, "gate1": None, "gate2": None}

    icis = np.diff(ts)
    icis_pos = icis[icis > 0]

    # Pre-filter: constant beacon
    if len(icis_pos) >= min_pkts:
        cv = float(np.std(icis_pos) / np.mean(icis_pos)) if np.mean(icis_pos) > 0 else 0
        if cv < 0.05:
            return {"classification": "REGULAR_BEACON", "confidence": 1.0,
                    "n_connections": n, "gate1": None, "gate2": None}

    # ---- Gate 1: Bounded Non-Periodic ----
    g1 = bounded_test(ts)

    if g1["label"] in ("INSUFFICIENT",):
        return {"classification": "INSUFFICIENT_DATA", "confidence": 0.0,
                "n_connections": n, "gate1": g1, "gate2": None}

    if g1["label"] != "BOUNDED":
        if g1["label"] == "NEAR_CONSTANT":
            return {"classification": "JITTERED_BEACON", "confidence": 0.80,
                    "n_connections": n, "gate1": g1, "gate2": None}
        if g1["label"] == "TRENDING":
            return {"classification": "BACKGROUND", "confidence": 1.0,
                    "n_connections": n, "gate1": g1, "gate2": None}
        return {"classification": "BACKGROUND", "confidence": 1.0,
                "n_connections": n, "gate1": g1, "gate2": None}

    # ---- Gate 2: Three-Gap + Discrepancy ----
    g2 = three_gap_test(ts)

    if g2["label"] == "THREE_GAP":
        conf = float((g1["beacon_score"] + g2["beacon_score"]) / 2.0)
        return {"classification": "ROTATION_BEACON", "confidence": round(conf, 3),
                "n_connections": n, "gate1": g1, "gate2": g2}

    return {"classification": "BACKGROUND", "confidence": 1.0,
            "n_connections": n, "gate1": g1, "gate2": g2}


# ============================================================
# Rotation sequence generators (for validation)
# ============================================================

def golden_rotation_times(n, ici_min=30.0, ici_max=120.0, jitter=0.0,
                          seed=42, start=1):
    """Generate intervals using golden ratio rotation."""
    rng = np.random.default_rng(seed)
    fracs = np.array([(i * PHI) % 1.0 for i in range(start, start + n)])
    ivs = ici_min + (ici_max - ici_min) * fracs
    if jitter > 0:
        ivs *= (1 + rng.uniform(-jitter, jitter, n))
        ivs = np.maximum(ivs, ici_min * 0.5)
    return list(np.concatenate([[0.0], np.cumsum(ivs)]))


def sqrt2_rotation_times(n, ici_min=30.0, ici_max=120.0):
    """Generate intervals using sqrt(2) rotation."""
    fracs = np.array([(i * np.sqrt(2)) % 1.0 for i in range(1, n + 1)])
    ivs = ici_min + (ici_max - ici_min) * fracs
    return list(np.concatenate([[0.0], np.cumsum(ivs)]))


def pi_rotation_times(n, ici_min=30.0, ici_max=120.0):
    """Generate intervals using pi rotation."""
    fracs = np.array([(i * np.pi) % 1.0 for i in range(1, n + 1)])
    ivs = ici_min + (ici_max - ici_min) * fracs
    return list(np.concatenate([[0.0], np.cumsum(ivs)]))
